### ISSUE TITLE
Any plans to publish this to crates.io?

### ISSUE THREAD

**Issue by Gskartwii** [nadavrot/layout#4]
Hi,
I've discovered the project from HN, as you probably have guessed. I would be excited to add this as a dependency for one of my personal projects. The way I'm used to is by configuring the dependency in `Cargo.toml`, which pulls crates from [crates.io](https://crates.io) (I think this is best practice). Are there any plans to publish this crate as well?

**Comment by bestouff** [comment]
Yes please; don't forget to explicitly say it's a graphviz replacement so it's easier to look for.

**Comment by coastalwhite** [comment]
It seems like a user by the name of @strake on GH already owns the name. Although not 100% sure, it also seems like he used a program to autoclaim certain names belonging to English words. So if you want to get it on crates.io with the *layout* name, either ask him or talk to the people from crates.io because autoclaiming is not allowed under the crates.io package policies.

[Source](https://crates.io/policies#squatting):
> "Using an automated tool to claim ownership of a large number of package names is not permitted. We reserve the right to block traffic or revoke ownership of any package we determine to have been claimed by an automated tool."

**Comment by bestouff** [comment]
Looks like a problem, indeed. Instead of waiting for an hypothetical resolution, how about finding another (smart and witty ?) name for your crate ?

**Comment by coastalwhite** [comment]
Some of my suggestions:

- Seraphs (Graphs → G-RS-aphs → Seraphs)
- Charter(s)
- Artisan (Maybe a bit too close to chartisan for laravel)

**Comment by azriel91** [comment]
Heya @nadavrot, would you have time to publish the crate?

Also, do you prefer keeping the `layout` name?
I'm happy to send through a renaming PR if that helps move things along, just let us know what name to use

**Comment by nadavrot** [comment]
@azriel91 I am happy to publish this to creates.io but I need some help. Do you mind helping me with the process?

**Comment by azriel91** [comment]
Heya, happy to do so.

There are [publishing docs](https://doc.rust-lang.org/stable/cargo/reference/publishing.html), but before that I'll do some maintenance and send through a PR:

1. Update dependencies.
2. Split the binary from library -- so that library consumers don't need to depend on `clap`.
3. Make logging an optional dependency (but enable-able through a feature) -- allows people to reduce dependency count / binary size.
4. Rename the crate so it can actually be published.

Do you have a crate name in mind for step 4?

**Comment by azriel91** [comment]
Heya @nadavrot, #10 prepares the crate for publishing.

I've made changes commit-by-commit for easy review, and added CI github action.
For the crate name, I've chosen `layout-rs`, but retained `layout` as the library name.

If you're happy with the changes, then publishing would be following the [docs](https://doc.rust-lang.org/stable/cargo/reference/publishing.html) to login to cargo, then:

1. `cd layout/layout` -- the library is in a subdirectory of the repo directory.
2. `cargo publish`

I should be on the [Rust Community discord server](https://discord.gg/rust-lang-community) today if you need help.

**Comment by nadavrot** [comment]
Thank you for your help @azriel91. I accepted the changes and landed the PR.

**Comment by nadavrot** [comment]
I published the package. I am not sure how to fix the issue where the layout-rs create does not have any docs, because the readme file is in the main create. What do you think?

**Comment by azriel91** [comment]
Hm, by "does not have any docs", where are you looking?

`layout-rs` does have docs on docs.rs: https://docs.rs/layout-rs/0.1.0/layout/

ohh, maybe you mean https://crates.io/crates/layout-rs

I'll add a link to `README.md` from the library crate -- though it would have to be published as `0.1.1`, we can't overwrite `0.1.0`
